version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tm_smeta_db
    environment:
      POSTGRES_USER: smeta_user
      POSTGRES_PASSWORD: smeta_password
      POSTGRES_DB: tm_smeta_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./server
    container_name: tm_smeta_server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://smeta_user:smeta_password@postgres:5432/tm_smeta_db?schema=public"
    depends_on:
      - postgres

volumes:
  pgdata:
